#!/usr/bin/env dash

if (xrandr | grep "HDMI1 connected"); then
	xrandr --output LVDS1 --off
	xrandr --output HDMI1 --auto
	bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 0
else
	MAIN=`xrandr | grep ' connected' | cut -f 1 -d ' '`
	bspc monitor $MAIN -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config split_ratio         0.52

bspc config window_gap          5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true
bspc config honor_size_hints false
bspc config ignore_ewmh_focus true
bspc config left_padding 0
bspc config left_monocle_padding 0

bspc config normal_border_color "#334046"
bspc config focused_border_color "#702936"
bspc config border_width 3

bspc rule -a Tint2 border=off layer=above manage=off

# trayer --edge left --align center -l --expand false &
sxhkd &
# setroot -z ~/Downloads/ubuntu-wallpapers-disco_19.04.2-0ubuntu1_all/data/usr/share/backgrounds/Disco_Dingo_Alt_Default_by_Abubakar_NK.png
# nm-applet    2>&1 > /dev/null &
# cbatticon &
