#! /bin/sh

bspc monitor -d 01 02 03 04 05 06 07 08 09 00

bspc rule -a Pidgin -d ^4
bspc rule -a Chromium -d ^2

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          8
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_border_color "#2b6d90"
bspc config focused_border_color "#ab6b74"
xsetroot -solid "#3c3c3c"
bspc config top_padding 22
setxkbmap us
xmodmap $HOME/.Xmodmap
$HOME/.config/bspwm/panel &
sh $HOME/.fehbg
sxhkd &
