#! /bin/dash

bspc monitor VGA1 -d 1 2 3 4 5 6 7 8 9 0

bspc config split_ratio         0.52

bspc config -m VGA1 border_width        3
bspc config -m VGA1 window_gap          15
bspc config -m VGA1 borderless_monocle  true
bspc config -m VGA1 gapless_monocle     true
bspc config -m VGA1 normal_border_color "#dddddd"
bspc config -m VGA1 focused_border_color "#919652"
sxhkd &
