#! /bin/sh

while true ; do
#echo "S ^i("$HOME"/.config/bspwm/bitmaps/wifi_01.xbm) $(iwgetid --raw)   ^i("$HOME"/.config/bspwm/bitmaps/battery.xbm) $(acpi -b | grep -o '[0-9]\+%')   ^i("$HOME"/.config/bspwm/bitmaps/clock.xbm) $(date '+%a %d, %H:%M')  "
	echo "S bat: $(acpi -b | grep -o '[0-9]\+%') | $(date '+%A %d, %R')  "
	# echo "S ssid: $(iwgetid --raw)  |  bat: $(acpi -b | grep -o '[0-9]\+%')  |  date: $(date '+%a %d, %H:%M')  "
	sleep 5
done
