#! /bin/sh

bspc desktop ^1 -n 1
bspc monitor -a 2 3 4 5 6 7 8 9 0
bspc rule -a Pidgin -d 4

bspc config split_ratio         0.52
bspc config border_width        3
bspc config window_gap          12
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config normal_border_color "#dbd4c1"
# bspc config normal_border_color "#373445"
# bspc config focused_border_color "#735162"
bspc config focused_border_color "#859900"
xsetroot -solid "#dbd4c1"
# hsetroot -solid "#373445"
bspc config top_padding 24

# xset fp+ ~/.fonts/stlarch
# xset fp+ ~/.fonts/artwiz
# xset fp rehash
xmodmap .dotfiles/.Xmodmap
sxhkd &
panel dzen2 &
calised
xgamma -gamma 0.8
xmodmap .Xmodmap
xrdb -merge .dotfiles/Xresources.light
setxkbmap us
#compton &
