#! /bin/bash

while true ; do
    #printf 'S\\r\\f9⇅\f1 $(iwgetid --raw)   \\f3♥ \\f1 $(acpi -b | grep -o "[0-9]\+%")   \\f6↻\\f1 $(date "+%a %d %H:%M")'
    date="\ue016 $(date '+%a %d, %H:%M')"
		bat="\ue03F $(acpi -b | grep -o '[0-9]\+%')"
    printf '\nS%b %b \n' "$bat" "$date"
    sleep 5
done
