
[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 15

[font.normal]
# family = "0xProto"
# family = "Anonymous Pro"
# family = "Cascadia Code PL"
# family = "CaskaydiaCove Nerd Font"
# family = "CaskaydiaCove Nerd Font Mono"
# family = "CommitMono"
# family = "Courier Prime"
# family = "Drafting* Mono"
# family = "Fira Code"
# family = "Geist Mono"
# family = "Hack"
# family = "IBM Plex Mono"
# family = "Inconsolata"
# family = "Input Mono"
# family = "Input Mono Compressed"
# family = "Input Mono Condensed"
# family = "Input Mono Narrow"
# family = "Intel One Mono"
# family = "JuliaMono"
# family = "Liberation Mono"
# family = "M PLUS Code Latin"
# family = "MesloLGL Nerd Font Mono"
# family = "MesloLGLDZ Nerd Font Mono"
# family = "MesloLGM Nerd Font Mono"
# family = "MesloLGMDZ Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "MesloLGSDZ Nerd Font Mono"
family = "Monaspace Argon"
# family = "Monaspace Krypton"
# family = "Monaspace Neon"
# family = "Monaspace Radon"
# family = "Monaspace Xenon"
# family = "Mononoki Nerd Font Mono"
# family = "Nimbus Mono PS"
# family = "Noto Color Emoji"
# family = "Rec Mono Casual"
# family = "Rec Mono Duotone"
# family = "Rec Mono Linear"
# family = "Rec Mono Semicasual"
# family = "Server Mono"
# family = "Source Code Pro"
# family = "Ubuntu Mono"
# family = "Victor Mono "

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true

[general]
import = ["/var/home/federico/.config/alacritty/colors/zenbones.toml"]
