import = ["/var/home/federico/.config/alacritty/colors/dayfox.toml"]

[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14

[font.normal]
# family = "Iosevka Term"
# family = "Rec Mono Casual"
# family = "Iosevka Term Slab"
family = "Fira Code"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
