[bell]
animation = "EaseOutExpo"
duration = 1000

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }

[font]
size = 16

[font.normal]
# family = "72 Mono"
# family = "0xProto"
# family = "Agave"
# family = "Adwaita Mono"
# family = "Anonymous Pro"
# family = "Atkinson Hyperlegible Mono"
# family = "Cascadia Code PL"
# family = "CommitMono"
# family = "Consolas"
# family = "Courier Prime"
family = "Cousine"
# family = "Drafting* Mono"
# family = "Fantasque Sans Mono"
# family = "Fira Code"
# family = "Geist Mono"
# family = "Hack"
# family = "Hermit"
# family = "iA Writer Mono V"
# family = "IBM Plex Mono"
# family = "Inconsolata"
# family = "Input Mono"
# family = "Input Mono Compressed"
# family = "Input Mono Condensed"
# family = "Input Mono Narrow"
# family = "Intel One Mono"
# family = "Iosevka Term SS05"
# family = "Iosevka Term SS14"
# family = "Jet Brains Mono"
# family = "JuliaMono"
# family = "Liberation Mono"
# family = "M PLUS Code Latin"
# family = "MesloLGL Nerd Font Mono"
# family = "MesloLGLDZ Nerd Font Mono"
# family = "MesloLGM Nerd Font Mono"
# family = "MesloLGMDZ Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "MesloLGSDZ Nerd Font Mono"
# family = "Monaspace Argon Var"
# family = "Monaspace Krypton Var"
# family = "Monaspace Neon Var"
# family = "Monaspace Radon Var"
# family = "Monaspace Xenon Var"
# family = "Monego"
# family = "Mononoki"
# family = "Nimbus Mono PS"
# family = "Noto Sans Mono"
# family = "Office Code Pro"
# family = "Overpass Mono"
# family = "PT Mono"
# family = "Rec Mono Casual"
# family = "Rec Mono Duotone"
# family = "Rec Mono Linear"
# family = "Rec Mono Semicasual"
# family = "Server Mono"
# family = "Source Code Pro"
# family = "Ubuntu Mono"
# family = "Victor Mono"

[font.offset]
x = 0
y = 0

# [hints]
# alphabet = "jfkdls;ahgurieowpq"
#
# [[hints.enabled]]
# command = "xdg-open"
# post_processing = true
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
# hyperlinks = true
# binding = {
# 	key = "U"
# 	mods = "Control|Shift"
# }
#
# [hints.enabled.mouse]
# enabled = true
# mods = "None"

[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "F11", action = "ToggleFullscreen" },
]

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true

[general]
import = ["/var/home/federico/.config/alacritty/colors/zenbones.toml"]
